% Table representation: [TableSchema|Entries]

:- module(tables, [table_name/2]).

table_name('movies', [["movie_id","title","genres"],
                      [1,"Toy Story (1995)","Animation,Children,Comedy"],
                      [2,"GoldenEye (1995)","Action,Adventure,Thriller"],
                      [3,"Four Rooms (1995)","Thriller"],
                      [4,"Get Shorty (1995)","Action,Comedy,Drama"],
                      [5,"Copycat (1995)","Crime,Drama,Thriller"],
                      [6,"Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)","Drama"],
                      [7,"Twelve Monkeys (1995)","Drama,Sci-Fi"],
                      [8,"Babe (1995)","Children,Comedy,Drama"],
                      [9,"Dead Man Walking (1995)","Drama"],
                      [10,"Richard III (1995)","Drama,War"],
                      [11,"Seven (Se7en) (1995)","Crime,Thriller"],
                      [12,"Usual Suspects, The (1995)","Crime,Thriller"],
                      [13,"Mighty Aphrodite (1995)","Comedy"],
                      [14,"Postino, Il (1994)","Drama,Romance"],
                      [15,"Mr. Holland's Opus (1995)","Drama"],
                      [16,"French Twist (Gazon maudit) (1995)","Comedy,Romance"],
                      [17,"From Dusk Till Dawn (1996)","Action,Comedy,Crime,Horror,Thriller"],
                      [18,"White Balloon, The (1995)","Drama"],
                      [19,"Antonia's Line (1995)","Drama"],
                      [20,"Schizopolis (1996)","Comedy"],
                      [21,"Cure, The (1995)","Drama"],
                      [22,"Tom and Huck (1995)","Adventure,Children"],
                      [23,"Gumby: The Movie (1995)","Animation,Children"],
                      [24,"Hideaway (1995)","Thriller"],
                      [25,"Visitors, The (Visiteurs, Les) (1993)","Comedy,Sci-Fi"],
                      [26,"Little Princess, The (1939)","Children,Drama"],
                      [27,"Nina Takes a Lover (1994)","Comedy,Romance"],
                      [28,"Bhaji on the Beach (1993)","Comedy,Drama"],
                      [29,"Raw (2016)","Horror,Drama"],
                      [30,"Nightwatch (1997)","Horror,Thriller"]]
          ).

table_name('ratings', [["first_name", "last_name", "movie_id", "rating"],
                       ["Vlad","Bengescu", 1, 9],
                       ["Anastasia","Tocilescu", 5, 3],
                       ["Andrei","Blaga", 3, 1],
                       ["Ion", "Ionescu", 2, 2],
                       ["Ion", "Bengescu", 8, 1],
                       ["Vasile","Dascalu", 13, 4],
                       ["Tudor","Arghezi", 12, 2],
                       ["Vlad","Dobrescu", 11, 5],
                       ["Ion", "Georgescu", 9, 7],
                       ["Vlad","Stanescu", 14, 3],
                       ["Petru","Calin", 7, 2],
                       ["Ion", "Bengescu", 6, 5],
                       ["Vlad","Flondor", 10, 10],
                       ["Anastasia","Papagheorghe", 4, 8],
                       ["Andrei","Patru", 20, 3],
                       ["Dan","Voinea", 16, 3],
                       ["Nichita", "Stanescu", 17, 5],
                       ["Ion", "Stanciu", 18, 2],
                       ["Vlad","Stanciu", 19, 8],
                       ["Anton","Dinescu", 15, 4],
                       ["Aurel","Diaconu", 22, 6],
                       ["Vasile","Enache", 25, 3],
                       ["Floricel","Coman", 30, 3],
                       ["Aurel","Man", 29, 6],
                       ["Paul","Stanescu", 21, 10],
                       ["Lucian","Blaga", 26, 5],
                       ["Alex","Tocilescu", 28, 4],
                       ["Petru","Ivan", 24, 4],
                       ["Dumitru","Calin", 23, 2],
                       ["Andrei","Papagheorghe", 27, 10]]
          ).

table_name('students', [["first_name", "last_name", "AA_grade", "PP_grade", "PC_grade", "PA_grade", "POO_grade"],
                        ["Ion", "Ionescu", 9, 7, 2, 1, 5],
                        ["Ion", "Georgescu", 5, 6, 4, 9, 6],
                        ["Ion", "Bengescu", 9, 6, 9, 3, 1],
                        ["Nichita", "Stanescu", 7, 2, 5, 4, 3],
                        ["Ion", "Stanciu", 6, 4, 3, 9, 1],
                        ["Ana","Stanescu", 8, 10, 9, 2, 7],
                        ["Andrei","Blaga", 10, 9, 8, 5, 3],
                        ["Anastasia","Tocilescu", 5, 1, 7, 10, 3],
                        ["Andrei","Patru", 1, 2, 4, 1, 7],
                        ["Petru","Calin", 8, 2, 6, 8, 4],
                        ["Anastasia","Papagheorghe", 8, 6, 7, 4, 6],
                        ["Anton","Dinescu", 10, 1, 6, 2, 5],
                        ["Vasile","Dascalu", 9, 10, 3, 10, 2],
                        ["Dan","Voinea", 9, 3, 2, 4, 5],
                        ["Vlad","Dobrescu", 9, 9, 1, 8, 9],
                        ["Vlad","Bengescu", 9, 6, 10 , 2, 7],
                        ["Vlad","Stanescu", 9, 7, 5, 9, 2],
                        ["Vlad","Stanciu", 8, 10, 9, 2, 7],
                        ["Vlad","Flondor", 3, 7, 1, 3, 9],
                        ["Tudor","Arghezi", 4, 8, 5, 6, 5],
                        ["Aurel","Diaconu", 8, 2, 1, 9, 6],
                        ["Vasile","Enache", 3, 1, 8, 6, 3],
                        ["Floricel","Coman", 1, 5, 8, 2, 3],
                        ["Aurel","Man", 7, 8, 5, 7, 3],
                        ["Paul","Stanescu", 8, 5, 2, 1, 10],
                        ["Lucian","Blaga", 2, 5, 10, 9 ,5],
                        ["Alex","Tocilescu", 5, 1, 2, 8, 4],
                        ["Petru","Ivan", 8, 7, 3, 3, 4],
                        ["Dumitru","Calin", 2, 7, 8, 4, 2],
                        ["Andrei","Papagheorghe", 2, 8, 10, 3, 10]]
          ).

table_name('students1', [["first_name", "last_name", "AA_grade", "PP_grade", "PC_grade", "PA_grade", "POO_grade"],
                        ["Raimond","Munteanu", 6, 5, 10, 9, 7],
                        ["Andrei","Alexandru", 7, 7, 2, 3, 5],
                        ["Dan","Alexe", 4, 5, 10, 9, 7],
                        ["Sergiu","Cristoiu", 7, 8, 1, 2, 5],
                        ["Andrei","Papagheorghe", 2, 8, 10, 3, 10]]
          ).

table_name('students2', [["first_name", "last_name", "AA_grade", "PP_grade", "PC_grade", "PA_grade", "POO_grade"],
                        ["Ion", "Voicu", 9, 7, 2, 1, 5],
                        ["Ion", "Bengescu", 9, 6, 9, 3, 1],
                        ["Vlad","Dobrescu", 9, 9, 1, 8, 9],
                        ["Andrei","Alexandru", 7, 7, 2, 3, 5],
                        ["Dan","Alexe", 4, 5, 10, 9, 7],
                        ["Andrei","Georgescu", 9, 7, 5, 9, 2],
                        ["Paul","Stanescu", 8, 5, 2, 1, 10],
                        ["Lucian","Blaga", 2, 5, 10, 9 ,5],
                        ["Sergiu","Cristoiu", 7, 8, 1, 2, 5]]
          ).
          
table_name('students3', [["first_name", "last_name", "AA_grade", "PP_grade", "PC_grade", "PA_grade", "POO_grade"],
                        ["Ion", "Antonescu", 9, 7, 2, 1, 5],
                        ["Cezar", "Ion", 9, 6, 9, 3, 1],
                        ["Vlad","Dobre", 9, 9, 1, 8, 9],
                        ["Andrei","Alexandru", 7, 7, 2, 3, 5],
                        ["Dan","Alexe", 4, 5, 10, 9, 7],
                        ["Andrei","Georgescu", 9, 7, 5, 9, 2],
                        ["Paul","Stanescu", 8, 5, 2, 1, 10],
                        ["Lucian","Blaga", 2, 5, 10, 9 ,5],
                        ["Sergiu","Cristoiu", 7, 8, 1, 2, 5]]
          ).
